FROM node:20-alpine AS build

WORKDIR /app

COPY . .
RUN corepack enable
RUN rm -f .pnp.cjs .pnp.loader.mjs .yarn/install-state.gz
RUN --mount=type=cache,target=/root/.yarn yarn install --immutable
RUN yarn build

FROM caddy

# https://kofi.sexy/blog/zero-downtime-render-disk
RUN setcap -r /usr/bin/caddy
COPY --from=build /app/dist /usr/share/caddy
COPY ./docker/Caddyfile.ozma /etc/caddy/Caddyfile
